spring:
   datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:bodega;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: 
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: create-drop
      properties:
         hibernate.dialect: org.hibernate.dialect.H2Dialect
   h2:
     console.enabled: true
     console.path: /h2

server:
   port: 8085
   servlet:
      context-path: /bodega
